/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmapTransformer;

import javax.imageio.ImageIO;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Random;

public class App {

    public static void main(String[] args) {

        try {
            BitMap bmp = new BitMap("main/resources/" + args[0]);
            if (args[2].equals("sunglasses-white")) {
                int sunglassColor = new Color(255, 255, 255).getRGB();
                bmp.putOnSunglasses(sunglassColor, 25, 45);
            }
            if (args[2].equals("sunglasses-black")) {
            int sunglassColor = new Color(0,0,0).getRGB();
                bmp.putOnSunglasses(sunglassColor, 25, 45);
            }
            if (args[2].equals("sunglasses-random")) {
                Random r = new Random();
            int sunglassColor = new Color(r.nextInt(255),r.nextInt(255),r.nextInt(255)).getRGB();
                bmp.putOnSunglasses(sunglassColor, 25, 45);
            }
            bmp.saveImage("main/resources/" + args[1]);
            System.out.println(args[0] + " successfully modified and saved as " + args[1]);
        }
        catch (Exception e) {
            e.printStackTrace();
            System.out.println("File not found. Arguments provided: args[0]: " + args[0] + " args[1]: " + args[1] + " args[2]: " + args[2]);
        }
    }
}
